--PARAMETERIZED CURSOR

DECLARE
	CURSOR C(NO NUMBER) IS SELECT*FROM EMP WHERE EID=NO;
	--TMP EMP%ROWTYPE;
	
BEGIN
	--OPEN C(4)
	FOR TMP IN C(3) LOOP
	
		DBMS_OUTPUT.PUT_LINE('EMP_NO:'|| TMP.EID);
		DBMS_OUTPUT.PUT_LINE('EMP_NAME:'|| TMP.ENAME);
		DBMS_OUTPUT.PUT_LINE('EMP_DEPT:'|| TMP.DEPTNO);
		DBMS_OUTPUT.PUT_LINE('EMP_SALARY:'|| TMP.SAL);
	END LOOP;
	--CLOSE C;
END;
/