--ONE CURSOR IS FOR FINDING DEPT WISE SALARY
--SECOND CURSOR IS FOR FINDIND AVERAGE SALARY

DECLARE
	E1 EMP%ROWTYPE;
	DNO EMP.DEPTNO%TYPE;
	SALARY EMP.SAL%TYPE;
	
	CURSOR C1(DN VARCHAR) IS SELECT*FROM EMP WHERE DEPTNO=DN;
	CURSOR C2(DN VARCHAR) IS SELECT DEPTNO,AVG(SAL) FROM EMP GROUP BY DEPTNO HAVING DEPTNO=DN;
	
BEGIN
--SHOW DEPT WISE SAL OF ALL EMPLOYEE
	DBMS_OUTPUT.PUT_LINE('DEPARTMENT WISE EMPLOYWEE SALARY');
	OPEN C1('HR');
	LOOP
	FETCH C1 INTO E1;
	EXIT WHEN C1%NOTFOUND;
	DBMS_OUTPUT.PUT_LINE(E1.DEPTNO||':'||E1.SAL);
	END LOOP;
	CLOSE C1;
	
--SHOW DEPTNO WISE AVG SAL
	DBMS_OUTPUT.PUT_LINE('DEPARTMENT WISE AVERAGE SALARY');
	OPEN C2('IT');
	
	LOOP
		FETCH C2 INTO DNO,SALARY;
		EXIT WHEN C2%NOTFOUND;
		DBMS_OUTPUT.PUT_LINE(DNO||':'||SALARY);
	END LOOP;
	CLOSE C2;
END;
/